name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Deploy to Render
      env:
        RENDER_API_KEY: ${{ secrets.staging }}
      run: |
        curl -X POST "https://api.render.com/v1/services/rnd_8YD0g8rYGNpshjMefbk0cGw362Mp/deploys" \
        -H "Authorization: Bearer $https://flask-book-store-app-i0t7.onrender.com \
        -d ''
